apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-activity-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: travel-activity-service
  template:
    metadata:
      labels:
        app: travel-activity-service
    spec:
      containers:
        - name: activity-service
          image: berkayalkn/travel-activity-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: backend-secrets 
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
spec:
  selector:
    app: travel-activity-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002