apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-geocoding-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: travel-geocoding-service
  template:
    metadata:
      labels:
        app: travel-geocoding-service
    spec:
      containers:
        - name: geocoding-service
          image: berkayalkn/travel-geocoding-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          resources: 
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: geocoding-service
spec:
  selector:
    app: travel-geocoding-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003