apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-frontend
  tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: travel-frontend
        tier: frontend
    spec:
      containers:
        - name: travel-frontend
          image: berkayalkn/travel-agent-frontend:v2
          ports:
            - containerPort: 8080 
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: travel-frontend-svc
spec:
  selector:
    app: travel-frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: travel-frontend-route
spec:
  to:
    kind: Service
    name: travel-frontend-svc
  port:
    targetPort: 8080
